[package]
name = "meta_ii_machine"
version = "0.1.0"
authors = ["Tom Rawcliffe <git@tomrawcliffe.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.0"